# Generated by Django 4.0.6 on 2022-09-27 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cover', models.ImageField(upload_to='')),
                ('library_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.library')),
            ],
        ),
        migrations.CreateModel(
            name='BookAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_serial', to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=5000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('library_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='account.library')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=2000)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('library_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.library')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(default=datetime.datetime.now)),
                ('date_to_be_returned', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to='core.book')),
                ('book_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_serial', to='core.bookamount')),
                ('borrowed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_name', to='core.membership')),
            ],
        ),
    ]
